### PR TITLE
Feature/add phq9 questionnaire cql json

### PR DESCRIPTION
**Pull request by achen2401**
generate elm JSON file from PHQ-9 cql

- pared down cql file by removing variables related to AUDIT-C questionnaire but not needed for PHQ-9 questionnaire.

### CODE REVIEW

**Comment by achen2401** [comment]
@mcjustin Were you able to get the elm json to generate from the [PHQ9 cql source file](https://github.com/uwcirg/asbi-screening-app/blob/0a845ea0e600f3689e924259e7d2a92c217621c8/src/cql/upstream-external/Phq9LogicLibrary.cql)?  I created a different branch here so I can try.  It seems to work for me now after some tweaks.  Here is what I see now in my local instance:  

Screen Shot 2022-04-11 at 3 14 41 PM

I see the score being calculated now, but am not certain if that is correct.

**Comment by mcjustin** [comment]
@achen2401  I'm already working on this cql file at https://github.com/uwcirg/asbi-screening-app/pull/5

**Comment by mcjustin** [comment]
@achen2401  I hadn't noticed that this PR was against my branch, and you'd made more progress than I had, so I've re-opened this :)

**Review by mcjustin — APPROVED** [review]

**Comment by mcjustin** [comment]
@achen2401 this works for me, I'm going to merge it. Thanks!

**Pull request merged**
